import { NextRequest, NextResponse } from "next/server";

import { AGENT_FILES } from "@/lib/agent";
import { meshToken, meshOrigin, primaryLanAddress } from "@/lib/config";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const COORDINATOR_PORT = Number(process.env.GRADMESH_COORDINATOR_PORT || 8000);

/**
 * The one-line join experience.
 *
 * A contributor pastes a single command. The script it fetches carries this
 * host's address and mesh token, finds a Python that PyTorch supports (and on
 * Windows offers to install one), downloads the agent, and hands over to
 * engine/setup_env.py, which is the same installer the host itself uses:
 * hardware detection, the PyTorch build for NVIDIA, Intel or Apple, a verified
 * kernel launch, then the worker.
 *
 * v4 carried the GPU rules inside these scripts, in PowerShell and in sh, next
 * to a third copy in the host's setup. They drifted. Now the scripts only find
 * Python, so there is one set of rules, in Python, tested once.
 */
export async function GET(request: NextRequest, context: { params: Promise<{ platform: string }> }) {
  const { platform } = await context.params;
  const host = request.headers.get("host");
  const webOrigin = meshOrigin(host);
  const hostname = new URL(webOrigin).hostname || primaryLanAddress();
  const coordinator = `http://${hostname}:${COORDINATOR_PORT}`;
  const token = meshToken();

  if (!token) {
    return new NextResponse(
      "# The mesh has not started yet. Run `npm run dev` on the host machine first.\n",
      { status: 503, headers: { "Content-Type": "text/plain" } }
    );
  }

  const body =
    platform === "ps1"
      ? powershellScript({ webOrigin, coordinator, token })
      : platform === "sh"
        ? shellScript({ webOrigin, coordinator, token })
        : null;

  if (!body) {
    return NextResponse.json({ detail: "Unknown platform. Use ps1 or sh." }, { status: 404 });
  }

  return new NextResponse(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

type ScriptContext = { webOrigin: string; coordinator: string; token: string };

function powershellScript({ webOrigin, coordinator, token }: ScriptContext): string {
  const files = AGENT_FILES.map((file) => `'${file}'`).join(", ");
  return `# GradMesh worker installer
# Generated by ${webOrigin}. Joins this machine's GPU to that mesh.
# Everything is installed under $HOME\\.gradmesh\\agent; nothing system-wide.

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$MeshWeb = '${webOrigin}'
$MeshCoordinator = '${coordinator}'
$MeshToken = '${token}'
$AgentRoot = Join-Path $HOME '.gradmesh\\agent'

Write-Host ""
Write-Host "GradMesh worker" -ForegroundColor Green
Write-Host "  joining $MeshCoordinator" -ForegroundColor DarkGray
Write-Host ""

# --- Python -----------------------------------------------------------------
# PyTorch 2.13 publishes wheels for Python 3.10 to 3.13. Each candidate is run
# with its arguments split explicitly: v4 passed $parts[1..0] for a bare
# 'python', which re-sent 'python' as an argument and never found a Microsoft
# Store install.
function Find-Python {
  foreach ($candidate in @('py -3.12', 'py -3.11', 'py -3.13', 'py -3.10', 'python', 'python3')) {
    $parts = @($candidate.Split(' '))
    $exe = $parts[0]
    $rest = @()
    if ($parts.Count -gt 1) { $rest = @($parts[1..($parts.Count - 1)]) }
    try {
      $version = & $exe @rest -c "import sys; print(sys.version_info.major * 100 + sys.version_info.minor)" 2>$null
      if ($LASTEXITCODE -eq 0 -and [int]$version -ge 310 -and [int]$version -le 313) {
        return ,(@($exe) + $rest)
      }
    } catch { }
  }
  return $null
}

$Python = Find-Python
if (-not $Python) {
  Write-Host "  Python 3.10 to 3.13 is needed and was not found." -ForegroundColor Yellow
  $winget = Get-Command winget -ErrorAction SilentlyContinue
  $answer = 'n'
  if ($winget) {
    try { $answer = Read-Host "  Install Python 3.12 for your user account now with winget? [Y/n]" } catch { $answer = 'n' }
  }
  if ($winget -and ($answer -eq '' -or $answer -match '^[Yy]')) {
    winget install --id Python.Python.3.12 -e --scope user --silent --accept-package-agreements --accept-source-agreements | Out-Host
    $env:Path = [Environment]::GetEnvironmentVariable('Path', 'User') + ';' + [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $Python = Find-Python
  }
  if (-not $Python) {
    Write-Host "  Install Python 3.12, then open a new PowerShell and run this command again:" -ForegroundColor Red
    Write-Host "    winget install Python.Python.3.12" -ForegroundColor Yellow
    Write-Host "    (or the installer from https://www.python.org/downloads/, with 'Add to PATH' ticked)" -ForegroundColor DarkGray
    return
  }
}
$PythonExe = $Python[0]
$PythonArgs = @()
if ($Python.Count -gt 1) { $PythonArgs = @($Python[1..($Python.Count - 1)]) }
Write-Host "  found Python: $($Python -join ' ')" -ForegroundColor Green

# --- Agent source -----------------------------------------------------------
New-Item -ItemType Directory -Force -Path $AgentRoot | Out-Null
Write-Host "  downloading the agent" -ForegroundColor DarkGray
foreach ($file in @(${files})) {
  $target = Join-Path $AgentRoot $file
  $attempt = 0
  while ($true) {
    try {
      Invoke-WebRequest -Uri "$MeshWeb/api/agent/$file" -OutFile $target -UseBasicParsing -TimeoutSec 60
      break
    } catch {
      $attempt += 1
      if ($attempt -ge 3) {
        Write-Host "  Could not download $file from $MeshWeb. Is this machine on the same network as the host?" -ForegroundColor Red
        return
      }
      Start-Sleep -Seconds 2
    }
  }
}

# --- Install and join ---------------------------------------------------------
# setup_env.py detects the GPU (NVIDIA, Intel Arc, or CPU-only), installs the
# matching PyTorch build into $AgentRoot\\.venv, verifies a kernel actually runs
# on it, and starts the worker. Run it again any time; it only installs what
# changed.
& $PythonExe @PythonArgs (Join-Path $AgentRoot 'setup_env.py') agent --server $MeshCoordinator --token $MeshToken --name $env:COMPUTERNAME
`;
}

function shellScript({ webOrigin, coordinator, token }: ScriptContext): string {
  const files = AGENT_FILES.join(" ");
  return `#!/bin/sh
# GradMesh worker installer
# Generated by ${webOrigin}. Joins this machine's GPU to that mesh.
# Everything is installed under ~/.gradmesh/agent; nothing system-wide.
set -e

MESH_WEB="${webOrigin}"
MESH_COORDINATOR="${coordinator}"
MESH_TOKEN="${token}"
AGENT_ROOT="$HOME/.gradmesh/agent"

printf '\\n\\033[32mGradMesh worker\\033[0m\\n'
printf '\\033[90m  joining %s\\033[0m\\n\\n' "$MESH_COORDINATOR"

# --- Python -----------------------------------------------------------------
# PyTorch 2.13 publishes wheels for Python 3.10 to 3.13. macOS's own
# /usr/bin/python3 is 3.9 (and, without the developer tools, a stub that opens
# an installer dialog), so it is never tried.
#
# On an Apple Silicon Mac the interpreter must also be arm64. An Intel build
# runs under Rosetta, where PyTorch has nothing to install, so every candidate
# is run through "arch -arm64": an Intel-only Python then fails the check
# instead of being picked. Homebrew's /opt/homebrew is arm64-only, so it goes
# first.
RUN=""
CANDIDATES="python3.12 python3.11 python3.13 python3.10 python3 python"
if [ "$(uname -s)" = "Darwin" ]; then
  if [ "$(sysctl -n hw.optional.arm64 2>/dev/null)" = "1" ]; then
    RUN="/usr/bin/arch -arm64"
  fi
  CANDIDATES="/opt/homebrew/bin/python3.12 /opt/homebrew/bin/python3.11 /opt/homebrew/bin/python3.13 /opt/homebrew/bin/python3.10
              /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
              /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
              /Library/Frameworks/Python.framework/Versions/3.13/bin/python3
              python3.12 python3.11 python3.13 python3.10
              /usr/local/bin/python3.12 /usr/local/bin/python3.11 /usr/local/bin/python3.13 python3"
fi
PYTHON=""
for candidate in $CANDIDATES; do
  resolved=$(command -v "$candidate" 2>/dev/null) || continue
  [ "$resolved" = "/usr/bin/python3" ] && [ "$(uname -s)" = "Darwin" ] && continue
  version=$($RUN "$resolved" -c 'import sys; print(sys.version_info.major * 100 + sys.version_info.minor)' 2>/dev/null || echo 0)
  if [ "$version" -ge 310 ] 2>/dev/null && [ "$version" -le 313 ] 2>/dev/null; then
    PYTHON="$resolved"
    break
  fi
done

if [ -z "$PYTHON" ]; then
  case "$(uname -s)" in
    Darwin)
      if [ -n "$RUN" ]; then
        printf '\\033[31m  An Apple Silicon (arm64) Python 3.10 to 3.13 is needed and was not found.\\033[0m\\n'
        printf '\\033[90m  An Intel Python runs under Rosetta, where PyTorch has no builds.\\033[0m\\n'
      else
        printf '\\033[31m  Python 3.10 to 3.13 is needed and was not found.\\033[0m\\n'
      fi
      printf '\\033[33m    brew install python@3.12\\033[0m\\n'
      printf '\\033[90m    (no Homebrew? https://brew.sh, or the macOS installer from https://www.python.org/downloads/)\\033[0m\\n' ;;
    *)
      printf '\\033[31m  Python 3.10 to 3.13 is needed and was not found.\\033[0m\\n'
      printf '\\033[33m    Ubuntu/Debian:  sudo apt install python3.12 python3.12-venv\\033[0m\\n'
      printf '\\033[33m    Fedora:         sudo dnf install python3.12\\033[0m\\n' ;;
  esac
  printf '\\033[90m  Then run this command again.\\033[0m\\n'
  exit 1
fi
printf '\\033[32m  found Python: %s\\033[0m\\n' "$PYTHON"

# --- Agent source -----------------------------------------------------------
mkdir -p "$AGENT_ROOT"
printf '\\033[90m  downloading the agent\\033[0m\\n'
fetch() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL --retry 3 --retry-delay 2 "$1" -o "$2"
  else
    wget -q --tries=3 "$1" -O "$2"
  fi
}
for file in ${files}; do
  if ! fetch "$MESH_WEB/api/agent/$file" "$AGENT_ROOT/$file"; then
    printf '\\033[31m  Could not download %s. Is this machine on the same network as the host?\\033[0m\\n' "$file"
    exit 1
  fi
done

# --- Install and join ---------------------------------------------------------
# setup_env.py detects the GPU (NVIDIA, Intel Arc, Apple Silicon or CPU-only),
# installs the matching PyTorch build into $AGENT_ROOT/.venv, verifies a kernel
# actually runs on it, and starts the worker. Safe to run again. On Apple
# Silicon it starts as arm64, so everything it launches is native too.
exec $RUN "$PYTHON" "$AGENT_ROOT/setup_env.py" agent \\
  --server "$MESH_COORDINATOR" \\
  --token "$MESH_TOKEN" \\
  --name "$(hostname)"
`;
}
