import { NextRequest, NextResponse } from "next/server";

import { AGENT_FILES } from "@/lib/agent";
import { meshToken, meshOrigin, primaryLanAddress } from "@/lib/config";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const COORDINATOR_PORT = Number(process.env.GRADMESH_COORDINATOR_PORT || 8000);

/**
 * The one-line join experience.
 *
 * This is the piece v3 was missing. A contributor pastes a single command; the
 * script it fetches carries this host's address and mesh token already baked
 * in, pulls the agent source, picks the PyTorch build that matches whatever
 * accelerator the machine actually has, and joins. No repository, no
 * requirements file, no reading a README on a second laptop.
 */
export async function GET(request: NextRequest, context: { params: Promise<{ platform: string }> }) {
  const { platform } = await context.params;
  const host = request.headers.get("host");
  const webOrigin = meshOrigin(host);
  const hostname = new URL(webOrigin).hostname || primaryLanAddress();
  const coordinator = `http://${hostname}:${COORDINATOR_PORT}`;
  const token = meshToken();

  if (!token) {
    return new NextResponse(
      "# The mesh has not started yet. Run `npm run dev` on the host machine first.\n",
      { status: 503, headers: { "Content-Type": "text/plain" } }
    );
  }

  const body =
    platform === "ps1"
      ? powershellScript({ webOrigin, coordinator, token })
      : platform === "sh"
        ? shellScript({ webOrigin, coordinator, token })
        : null;

  if (!body) {
    return NextResponse.json({ detail: "Unknown platform. Use ps1 or sh." }, { status: 404 });
  }

  return new NextResponse(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

type ScriptContext = { webOrigin: string; coordinator: string; token: string };

function powershellScript({ webOrigin, coordinator, token }: ScriptContext): string {
  const files = AGENT_FILES.map((file) => `'${file}'`).join(", ");
  return `# GradMesh worker installer
# Generated by ${webOrigin}. Joins this machine's GPU to that mesh.

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$MeshWeb = '${webOrigin}'
$MeshCoordinator = '${coordinator}'
$MeshToken = '${token}'
$AgentRoot = Join-Path $HOME '.gradmesh\\agent'
$VenvDir = Join-Path $AgentRoot '.venv'

function Write-Step($text) { Write-Host "  $text" -ForegroundColor DarkGray }
function Write-Ok($text) { Write-Host "  $text" -ForegroundColor Green }

Write-Host ""
Write-Host "GradMesh worker" -ForegroundColor Green
Write-Host "  joining $MeshCoordinator" -ForegroundColor DarkGray
Write-Host ""

# --- Python -----------------------------------------------------------------
$PythonExe = $null
foreach ($candidate in @('py -3.12', 'py -3.11', 'py -3', 'python', 'python3')) {
  $parts = $candidate.Split(' ')
  try {
    $version = & $parts[0] $parts[1..($parts.Length - 1)] -c "import sys; print(sys.version_info.major * 100 + sys.version_info.minor)" 2>$null
    if ($LASTEXITCODE -eq 0 -and [int]$version -ge 309) { $PythonExe = $candidate; break }
  } catch { }
}

if (-not $PythonExe) {
  Write-Host "  Python 3.9 or newer is required." -ForegroundColor Red
  Write-Host "  Install it, then run this command again:" -ForegroundColor Red
  Write-Host "    winget install Python.Python.3.12" -ForegroundColor Yellow
  return
}
Write-Ok "found $PythonExe"

# --- Agent source -----------------------------------------------------------
New-Item -ItemType Directory -Force -Path $AgentRoot | Out-Null
Write-Step "downloading the agent"
foreach ($file in @(${files})) {
  Invoke-WebRequest -Uri "$MeshWeb/api/agent/$file" -OutFile (Join-Path $AgentRoot $file) -UseBasicParsing
}
Write-Ok "agent downloaded"

# --- Accelerator ------------------------------------------------------------
# The PyTorch build is chosen from the GPU's compute capability, not its name.
# A CUDA wheel only contains kernels for the architectures it was compiled
# against: the 12.1 build covers sm_50 to sm_90, which stops at Hopper. A
# Blackwell card, meaning the RTX 50 series at compute 12.0, installs that build
# cleanly, reports CUDA as available, and then fails every kernel launch with
# "no kernel image is available for execution on the device". nvidia-smi reports
# the capability without PyTorch present, which is how this is decided up front
# rather than discovered during the first training round.
$Requirements = 'requirements-train-cpu.txt'; $Backend = 'auto'; $Label = 'CPU'
$ComputeCap = $null
$GpuName = ''

try {
  $smi = & nvidia-smi --query-gpu=name,compute_cap --format=csv,noheader 2>$null
  if ($LASTEXITCODE -eq 0 -and $smi) {
    foreach ($line in @($smi)) {
      $parts = $line -split ','
      if ($parts.Length -ge 2) {
        $cap = 0.0
        if ([double]::TryParse($parts[1].Trim(), [ref]$cap)) {
          if ($null -eq $ComputeCap -or $cap -gt $ComputeCap) {
            $ComputeCap = $cap; $GpuName = $parts[0].Trim()
          }
        }
      }
    }
  }
} catch { }

if ($null -ne $ComputeCap) {
  if ($ComputeCap -ge 12.0) {
    $Requirements = 'requirements-train-cu128.txt'; $Backend = 'cuda'
    $Label = "NVIDIA CUDA 12.8 (compute $ComputeCap, Blackwell or newer)"
  } elseif ($ComputeCap -ge 5.0) {
    $Requirements = 'requirements-train-cu121.txt'; $Backend = 'cuda'
    $Label = "NVIDIA CUDA 12.1 (compute $ComputeCap)"
  } else {
    $Label = "CPU ($GpuName at compute $ComputeCap is too old for current PyTorch)"
  }
} else {
  $gpuNames = ''
  try { $gpuNames = ((Get-CimInstance Win32_VideoController).Name -join ';').ToLower() } catch { }
  if ($gpuNames -match 'nvidia|geforce|rtx|quadro|tesla') {
    # An NVIDIA card with no working nvidia-smi. 12.1 covers everything that
    # predates the compute_cap field, so it is the safer guess.
    $Requirements = 'requirements-train-cu121.txt'; $Backend = 'cuda'
    $Label = 'NVIDIA CUDA 12.1 (nvidia-smi unavailable, assuming pre-Blackwell)'
  } elseif ($gpuNames -match 'intel\\(r\\) arc|intel arc') {
    $Requirements = 'requirements-xpu.txt'; $Backend = 'xpu'; $Label = 'Intel XPU'
  }
}
Write-Ok "detected $Label"

# --- Environment ------------------------------------------------------------
$VenvPython = Join-Path $VenvDir 'Scripts\\python.exe'
if (-not (Test-Path $VenvPython)) {
  Write-Step "creating a private Python environment"
  $parts = $PythonExe.Split(' ')
  & $parts[0] $parts[1..($parts.Length - 1)] -m venv $VenvDir
}

Write-Step "installing $Label PyTorch, this takes a few minutes the first time"
& $VenvPython -m pip install --upgrade pip --quiet --disable-pip-version-check
& $VenvPython -m pip install --quiet --disable-pip-version-check -r (Join-Path $AgentRoot $Requirements)
if ($LASTEXITCODE -ne 0) {
  Write-Host "  Install failed. Nothing was changed outside $AgentRoot." -ForegroundColor Red
  return
}
Write-Ok "dependencies ready"

# --- Join -------------------------------------------------------------------
Write-Host ""
Write-Host "  Contributing this GPU. Press Ctrl+C to leave the mesh." -ForegroundColor Green
Write-Host ""
& $VenvPython (Join-Path $AgentRoot 'worker.py') --server-url $MeshCoordinator --token $MeshToken --backend $Backend --name $env:COMPUTERNAME --discover
`;
}

function shellScript({ webOrigin, coordinator, token }: ScriptContext): string {
  const files = AGENT_FILES.join(" ");
  return `#!/bin/sh
# GradMesh worker installer
# Generated by ${webOrigin}. Joins this machine's GPU to that mesh.
set -e

MESH_WEB="${webOrigin}"
MESH_COORDINATOR="${coordinator}"
MESH_TOKEN="${token}"
AGENT_ROOT="$HOME/.gradmesh/agent"
VENV_DIR="$AGENT_ROOT/.venv"

printf '\\n\\033[32mGradMesh worker\\033[0m\\n'
printf '\\033[90m  joining %s\\033[0m\\n\\n' "$MESH_COORDINATOR"

# --- Python -----------------------------------------------------------------
PYTHON=""
for candidate in python3.12 python3.11 python3 python; do
  if command -v "$candidate" >/dev/null 2>&1; then
    version=$("$candidate" -c 'import sys; print(sys.version_info.major * 100 + sys.version_info.minor)' 2>/dev/null || echo 0)
    if [ "$version" -ge 309 ] 2>/dev/null; then PYTHON="$candidate"; break; fi
  fi
done

if [ -z "$PYTHON" ]; then
  printf '\\033[31m  Python 3.9 or newer is required.\\033[0m\\n'
  printf '\\033[33m    macOS:  brew install python@3.12\\n    Linux:  sudo apt install python3 python3-venv\\033[0m\\n'
  exit 1
fi
printf '\\033[32m  found %s\\033[0m\\n' "$PYTHON"

# --- Agent source -----------------------------------------------------------
mkdir -p "$AGENT_ROOT"
printf '\\033[90m  downloading the agent\\033[0m\\n'
for file in ${files}; do
  curl -fsSL "$MESH_WEB/api/agent/$file" -o "$AGENT_ROOT/$file"
done

# --- Accelerator ------------------------------------------------------------
# Chosen from compute capability, not the card's name. See the note in the
# PowerShell variant: a CUDA wheel only carries kernels for the architectures it
# was built against, and a Blackwell card on the 12.1 build fails every kernel
# launch despite installing and detecting cleanly.
REQUIREMENTS="requirements-train-cpu.txt"; BACKEND="auto"; LABEL="CPU"
COMPUTE_CAP=""

if command -v nvidia-smi >/dev/null 2>&1; then
  COMPUTE_CAP=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null \\
    | tr -d ' ' | sort -rn | head -n 1 || true)
fi

if [ -n "$COMPUTE_CAP" ]; then
  CAP_MAJOR=\${COMPUTE_CAP%%.*}
  if [ "$CAP_MAJOR" -ge 12 ] 2>/dev/null; then
    REQUIREMENTS="requirements-train-cu128.txt"; BACKEND="cuda"
    LABEL="NVIDIA CUDA 12.8 (compute $COMPUTE_CAP, Blackwell or newer)"
  elif [ "$CAP_MAJOR" -ge 5 ] 2>/dev/null; then
    REQUIREMENTS="requirements-train-cu121.txt"; BACKEND="cuda"
    LABEL="NVIDIA CUDA 12.1 (compute $COMPUTE_CAP)"
  else
    LABEL="CPU (compute $COMPUTE_CAP is too old for current PyTorch)"
  fi
else
  GPU=""
  if command -v lspci >/dev/null 2>&1; then
    GPU=$(lspci 2>/dev/null | grep -iE 'vga|3d|display' | tr '[:upper:]' '[:lower:]' || true)
  fi
  case "$GPU" in
    *nvidia*|*geforce*)
      REQUIREMENTS="requirements-train-cu121.txt"; BACKEND="cuda"
      LABEL="NVIDIA CUDA 12.1 (nvidia-smi unavailable, assuming pre-Blackwell)" ;;
    *"intel corporation dg2"*|*"intel arc"*)
      REQUIREMENTS="requirements-xpu.txt"; BACKEND="xpu"; LABEL="Intel XPU" ;;
  esac
fi
printf '\\033[32m  detected %s\\033[0m\\n' "$LABEL"

# --- Environment ------------------------------------------------------------
if [ ! -x "$VENV_DIR/bin/python" ]; then
  printf '\\033[90m  creating a private Python environment\\033[0m\\n'
  "$PYTHON" -m venv "$VENV_DIR"
fi

printf '\\033[90m  installing %s PyTorch, this takes a few minutes the first time\\033[0m\\n' "$LABEL"
"$VENV_DIR/bin/python" -m pip install --upgrade pip --quiet --disable-pip-version-check
"$VENV_DIR/bin/python" -m pip install --quiet --disable-pip-version-check -r "$AGENT_ROOT/$REQUIREMENTS"
printf '\\033[32m  dependencies ready\\033[0m\\n\\n'

# --- Join -------------------------------------------------------------------
printf '\\033[32m  Contributing this GPU. Press Ctrl+C to leave the mesh.\\033[0m\\n\\n'
exec "$VENV_DIR/bin/python" "$AGENT_ROOT/worker.py" \\
  --server-url "$MESH_COORDINATOR" \\
  --token "$MESH_TOKEN" \\
  --backend "$BACKEND" \\
  --name "$(hostname)" \\
  --discover
`;
}
